# Generated by Django 4.2.3 on 2023-07-05 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
